<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <gazebo>
    <plugin name='diff_drive' filename='libgazebo_ros_diff_drive.so'>
      <ros>
        <namespace>/demo</namespace>
      </ros>

      <always_on>true</always_on>
      <update_rate>40</update_rate>

      <!-- wheels -->
      <left_joint>drivewhl_l_joint</left_joint>
      <right_joint>drivewhl_r_joint</right_joint>

      <!-- kinematics -->
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_diameter>${wheel_radius * 2}</wheel_diameter>
      <wheel_torque>${wheel_torque}</wheel_torque>

      <!-- limits -->	
      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>

      <!-- output -->
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>

      <command_topic>cmd_vel</command_topic>
      <odometry_topic>odom</odometry_topic>

      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>
    </plugin>

    <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
      <always_on>true</always_on>
      <update_rate>100.0</update_rate>
      <body_name>base_link</body_name>
      <topic_name>simple_controller/absolute_position</topic_name>
      <gaussian_noise>0</gaussian_noise>
      <frame_name>map</frame_name>
      <xyz_offsets>0 0 0</xyz_offsets>
      <rpy_offsets>0 0 0</rpy_offsets>
    </plugin>
  </gazebo>

  <gazebo reference="drivewhl_l_link">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <min_depth>0.001</min_depth>
    <max_vel>1.0</max_vel>
  </gazebo>

  <gazebo reference="drivewhl_r_link">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <min_depth>0.001</min_depth>
    <max_vel>1.0</max_vel>
  </gazebo>

  <gazebo reference="front_caster_link">
    <mu1>0.0</mu1>
    <mu2>0.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <min_depth>0.001</min_depth>
    <max_vel>1.0</max_vel>
  </gazebo>

  <gazebo reference="wall_sensor_link">
    <sensor type="ray" name="wall_sensor">
      <always_on>true</always_on>
      <update_rate>20.0</update_rate>
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <ray>
        <scan>
          <horizontal>
            <samples>1</samples>
            <resolution>1</resolution>
            <min_angle>0</min_angle>
            <max_angle>0</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.0160</min>
          <max>0.04</max>
          <resolution>0.1</resolution>
        </range>
      </ray>
    </sensor>
  </gazebo>

  <gazebo reference="left_cliff_sensor_link">
    <sensor type="ray" name="left_cliff_sensor">
      <always_on>true</always_on>
      <update_rate>20.0</update_rate>
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <ray>
        <scan>
          <horizontal>
            <samples>1</samples>
            <resolution>1</resolution>
            <min_angle>0</min_angle>
            <max_angle>0</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.01</min>
          <max>0.04</max>
          <resolution>0.1</resolution>
        </range>
      </ray>
    </sensor>
  </gazebo>

  <gazebo reference="right_cliff_sensor_link">
    <sensor type="ray" name="right_cliff_sensor">
      <always_on>true</always_on>
      <update_rate>20.0</update_rate>
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <ray>
        <scan>
          <horizontal>
            <samples>1</samples>
            <resolution>1</resolution>
            <min_angle>0</min_angle>
            <max_angle>0</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.01</min>
          <max>0.04</max>
          <resolution>0.1</resolution>
        </range>
      </ray>
    </sensor>
  </gazebo>

  <gazebo reference="leftfront_cliff_sensor_link">
    <sensor type="ray" name="leftfront_cliff_sensor">
      <always_on>true</always_on>
      <update_rate>20.0</update_rate>
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <ray>
        <scan>
          <horizontal>
            <samples>1</samples>
            <resolution>1</resolution>
            <min_angle>0</min_angle>
            <max_angle>0</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.01</min>
          <max>0.04</max>
          <resolution>0.1</resolution>
        </range>
      </ray>
    </sensor>
  </gazebo>

  <gazebo reference="rightfront_cliff_sensor_link">
    <sensor type="ray" name="rightfront_cliff_sensor">
      <always_on>true</always_on>
      <update_rate>20.0</update_rate>
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <ray>
        <scan>
          <horizontal>
            <samples>1</samples>
            <resolution>1</resolution>
            <min_angle>0</min_angle>
            <max_angle>0</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.01</min>
          <max>0.04</max>
          <resolution>0.1</resolution>
        </range>
      </ray>
    </sensor>
  </gazebo>

</robot>
